global.botNameList=ds_list_create()
ds_list_add(global.botNameList,"Homer Simpson")
ds_list_add(global.botNameList,"Marge Simpson")
ds_list_add(global.botNameList,"Bart Simpson")
ds_list_add(global.botNameList,"Lisa Simpson")
ds_list_add(global.botNameList,"Maggie Simpson")
ds_list_add(global.botNameList,"Abraham Simpson")
ds_list_add(global.botNameList,"Patty Bouvier")
ds_list_add(global.botNameList,"Selma Bouvier")
ds_list_add(global.botNameList,"Mona Simpson")
ds_list_add(global.botNameList,"Jacqueline Bouvier")
ds_list_add(global.botNameList,"Montgomery Burns")
ds_list_add(global.botNameList,"Waylon Smithers")
ds_list_add(global.botNameList,"Moe Szyslak")
ds_list_add(global.botNameList,"Barney Gumble")
ds_list_add(global.botNameList,"Kent Brockman")
ds_list_add(global.botNameList,"Mayor Quimby")
ds_list_add(global.botNameList,"Lenny Leonard")
ds_list_add(global.botNameList,"Carl Carlson")
ds_list_add(global.botNameList,"Krusty The Clown")
ds_list_add(global.botNameList,"Dr. Hibbert")
ds_list_add(global.botNameList,"Ned Flanders")
ds_list_add(global.botNameList,"Rod Flanders")
ds_list_add(global.botNameList,"Todd Flanders")
ds_list_add(global.botNameList,"Maude Flanders")
ds_list_add(global.botNameList,"Kang")
ds_list_add(global.botNameList,"Kodos")
ds_list_add(global.botNameList,"Milhouse Van Houten")
ds_list_add(global.botNameList,"Sherri")
ds_list_add(global.botNameList,"Terri")
ds_list_add(global.botNameList,"Nelson Muntz")
ds_list_add(global.botNameList,"Comic Book Guy")
ds_list_add(global.botNameList,"Apu") //Nahasapeemapetilon
ds_list_add(global.botNameList,"Martin Prince")
ds_list_add(global.botNameList,"Seymour Skinner")
ds_list_add(global.botNameList,"Chief Clancy Wiggum")
ds_list_add(global.botNameList,"Ralph Wiggum")
ds_list_add(global.botNameList,"Jasper Beardly")
ds_list_add(global.botNameList,"Captain McCallister")
ds_list_add(global.botNameList,"Otto Mann")
ds_list_add(global.botNameList,"Bumblebee Man")
ds_list_add(global.botNameList,"Itchy")
ds_list_add(global.botNameList,"Scratchy")
ds_list_add(global.botNameList,"Poochie")
ds_list_add(global.botNameList,"Jimbo Jones")
ds_list_add(global.botNameList,"Snake Jailbird")
ds_list_add(global.botNameList,"Fat Tony D'Amico")
ds_list_add(global.botNameList,"Sideshow Bob")
ds_list_add(global.botNameList,"Sideshow Cecil")
ds_list_add(global.botNameList,"Sideshow Mel")
ds_list_add(global.botNameList,"Sideshow Raheem")
ds_list_add(global.botNameList,"Janey Powell")
ds_list_add(global.botNameList,"Ranier Wolfcastle")
ds_list_add(global.botNameList,"Dewey Largo")
ds_list_add(global.botNameList,"Gary Chalmers") //Superintendent
ds_list_add(global.botNameList,"Agnes Skinner")
ds_list_add(global.botNameList,"Edna Krabappel")
ds_list_add(global.botNameList,"Elizabeth Hoover")
ds_list_add(global.botNameList,"Groundskeeper Willie")
ds_list_add(global.botNameList,"Cletus Spuckler")
ds_list_add(global.botNameList,"Hans Moleman")
ds_list_add(global.botNameList,"Dolph Starbeam")
ds_list_add(global.botNameList,"Professor John Frink")
ds_list_add(global.botNameList,"Kearney Zzyzwicz")
ds_list_add(global.botNameList,"Squeaky Voice Teen")
ds_list_add(global.botNameList,"Wendell Borton")
ds_list_add(global.botNameList,"Troy McClure")
ds_list_add(global.botNameList,"Lionel Hutz")
ds_list_add(global.botNameList,"Judge Snyder")
ds_list_add(global.botNameList,"Lou")
ds_list_add(global.botNameList,"Eddie")
ds_list_add(global.botNameList,"Reverend Lovejoy")
ds_list_add(global.botNameList,"Helen Lovejoy")
ds_list_add(global.botNameList,"Uter")
ds_list_add(global.botNameList,"Manjula")
ds_list_add(global.botNameList,"Kirk Van Houten")
ds_list_add(global.botNameList,"Luann Van Houten")
ds_list_add(global.botNameList,"Arnie Pye")
ds_list_add(global.botNameList,"Marvin Monroe")
ds_list_add(global.botNameList,"Drederick Tatum")
ds_list_add(global.botNameList,"Disco Stu")
ds_list_add(global.botNameList,"Hyman Krustofski")
ds_list_add(global.botNameList,"Martin Prince")
ds_list_add(global.botNameList,"Duffman")
ds_list_add(global.botNameList,"Lunchlady Doris")
ds_list_add(global.botNameList,"Artie Ziff")
ds_list_add(global.botNameList,"Gabbo")
ds_list_add(global.botNameList,"Bleeding Gums Murphy")
ds_list_add(global.botNameList,"Blinky")
ds_list_add(global.botNameList,"Lance Murdock")
ds_list_add(global.botNameList,"Dondelinger")
ds_list_add(global.botNameList,"Doctor Colossus")
ds_list_add(global.botNameList,"Radioactive Man")
ds_list_add(global.botNameList,"Fallout Boy")
ds_list_add(global.botNameList,"Jebidiah Springfield")
ds_list_add(global.botNameList,"Jub-Jub")
ds_list_add(global.botNameList,"Lurleen Lumpkin")
ds_list_add(global.botNameList,"Mary Bailey")
ds_list_add(global.botNameList,"Mr. Teeny")
ds_list_add(global.botNameList,"Princess Kashmir")
ds_list_add(global.botNameList,"Roger Meyers Jr.")
ds_list_add(global.botNameList,"Ruth Powers")
ds_list_add(global.botNameList,"Stampy")
ds_list_add(global.botNameList,"Hank Scorpio")
ds_list_add(global.botNameList,"Frank Grimes")
ds_list_add(global.botNameList,"Shary Bobbins")
ds_list_add(global.botNameList,"Snowball I")
ds_list_add(global.botNameList,"Snowball II")
ds_list_add(global.botNameList,"Snowball III")
ds_list_add(global.botNameList,"Snowball IV")
ds_list_add(global.botNameList,"Snowball V")
ds_list_add(global.botNameList,"Gil Gunderson")
ds_list_add(global.botNameList,"Herman Hermann")
ds_list_add(global.botNameList,"Dr. Nick Riviera")
ds_list_add(global.botNameList,"Akira")
ds_list_add(global.botNameList,"McBain")
ds_list_add(global.botNameList,"Herbert Powell")
ds_list_add(global.botNameList,"Mindy Simmons")
ds_list_add(global.botNameList,"Mr. Bergstrom")
ds_list_add(global.botNameList,"Lucius Sweet")
ds_list_add(global.botNameList,"Scott Christian")
ds_list_add(global.botNameList,"Don Brodka")
ds_list_add(global.botNameList,"Rex Banner")
ds_list_add(global.botNameList,"Ms. Botz")
ds_list_add(global.botNameList,"Lester")
ds_list_add(global.botNameList,"Amber Dempsey")
ds_list_add(global.botNameList,"Jessica Lovejoy")
ds_list_add(global.botNameList,"Laura Powers")
ds_list_add(global.botNameList,"Allison Taylor")
ds_list_add(global.botNameList,"Larry Burns")
ds_list_add(global.botNameList,"Freddie Quimby")
ds_list_add(global.botNameList,"Chester J. Lampwick")
ds_list_add(global.botNameList,"Hugh Parkfield")
ds_list_add(global.botNameList,"Lyle Lanley")
ds_list_add(global.botNameList,"Stacy Lovell")
ds_list_add(global.botNameList,"Frank Ormand")
ds_list_add(global.botNameList,"Bea Simmons")
ds_list_add(global.botNameList,"Lindsay Naegle")
ds_list_add(global.botNameList,"Cookie Kwan")
ds_list_add(global.botNameList,"Lois Pennycandy")
ds_list_add(global.botNameList,"Alice Glick")
ds_list_add(global.botNameList,"Llewellyn Sinclair")
ds_list_add(global.botNameList,"General Sherman")
ds_list_add(global.botNameList,"Blue Haired Lawyer")
ds_list_add(global.botNameList,"Crazy Cat Lady")
ds_list_add(global.botNameList,"Happy Little Elves")

return ds_list_find_value(global.botNameList,irandom(ds_list_size(global.botNameList)-1))

/*
Capital City Goofball - too long
Jacques - no 2nd name
Santa's Little Helper - too long
*/
